In [3]:
import tensorflow as tf
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### Indexing tensors
Tensors can be indexed just like Python lists

In [4]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [5]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [6]:
some_list[:1]

[1]

In [12]:
#Get first element from each dimension for each inde except for final one

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
# Create a rank 2 tesnor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [18]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [19]:
# Get the last time of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [20]:
#Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [23]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [28]:
tf.expand_dims(rank_2_tensor,axis=0) #axpand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [29]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Maniulating tensors (tensor opperations)

**Basic operations**

`+` , `-` , `*` , `/`

In [34]:
# You can a values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
# Originial tensor is unchanged 
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [36]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [37]:
#Subtraction 
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [38]:
#We can use the tensorflow built in funciton too
tf.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### **Matrix Multiplication**

In ML,MM is one of the most complex operation

In [46]:
tensor , tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [44]:
#Matri multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [45]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [47]:
#Matrix multiplication with pyton operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
#Create a tenor((3,2)

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
#Create a another (3,2) tensor
Y = tf.constant([[7,8],
                 [9,8],
                 [11,12]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9,  8],
        [11, 12]], dtype=int32)>)

In [50]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8,  8, 12]], dtype=int32)>

In [51]:
Y


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9,  8],
       [11, 12]], dtype=int32)>

In [59]:
tf.matmul(tensor,tensor,transpose_b=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149,  58],
       [ 58,  25]], dtype=int32)>

In [54]:
#Let's change the shae of Y
tf.reshape(Y,shape = (2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [ 8, 11, 12]], dtype=int32)>

In [56]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9,  8],
       [11, 12]], dtype=int32)>

In [57]:
X @ tf.reshape(Y,shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  30,  33],
       [ 53,  68,  75],
       [ 83, 106, 117]], dtype=int32)>

In [61]:
#Try matri multiplcation with transpose rather than reshape
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  25,  35],
       [ 53,  59,  81],
       [ 83,  93, 127]], dtype=int32)>



```
# This is formatted as code
```

**The dot product**

You can do MM by
* `tf.matmuk()`
* `tf.tesnordot()`

In [70]:
# Perform the dot product on  an Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  92],
       [116, 120]], dtype=int32)>

In [72]:
#Perform matri multiplicationn between X an Y(transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  25,  35],
       [ 53,  59,  81],
       [ 83,  93, 127]], dtype=int32)>

In [73]:
#Perform matri multiplication between  and Y(Reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  30,  33],
       [ 53,  68,  75],
       [ 83, 106, 117]], dtype=int32)>

In [74]:
#Check the valuse of Y, reshape Y and transposed Y
print("Normal y:")
print(Y,"\n")#"\n" is for newline

print("Y reshaped to (2,3)")
print(tf.reshape(Y,shape=(2,3)),"\n")

print("Y transposed : ")
print(tf.transpose(Y))



Normal y:
tf.Tensor(
[[ 7  8]
 [ 9  8]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [ 8 11 12]], shape=(2, 3), dtype=int32) 

Y transposed : 
tf.Tensor(
[[ 7  9 11]
 [ 8  8 12]], shape=(2, 3), dtype=int32)
