# fundamentals of tensorflow
 
More secifically we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Maniulating tensors
* Tensors and numpy
* Using @tf.functions(a way to speed up your regular functions)
* Using gu with tensorflows(or TPUs)
* Excercise to try for yourself

## Introduction to tensors  

In [2]:
#Import tensorflow

import tensorflow as tf
print(tf.__version__)


2.9.2


In [3]:
# Create tensors with tf.constant()
scalar  =  tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimensions of a tensor(ndim stand for number of dimensions)
scalar.ndim

0

In [5]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check the dimension of our vector
vector.ndim

1

In [7]:
#create a matrix(more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
#check the dimension of our matrix
matrix.ndim

2

In [9]:
#Create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype = tf.float16) #specify th data tye ith dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#Whats the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
#Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we've created so far:

* Scalar: A single number
* Vector : a number with direction(e.g. wind seed and direction)
* Matrix : A 2-dimension array of number
*Tensor : an n-dimension array of number (where n can be any number , a 0-dimensional tensor if scalar,a 1-dimensional tensor is a vector)

### Creating tensors with tf.variable

In [13]:
#create the same tensor with tf.Variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#Lets try to change one of element
changable_tensor[0] = 7
changable_tensor

TypeError: ignored

In [15]:
#how about we try to assign()
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
#Lets try to change unchangable tensor 
unchangable_tensor[0].assign(7)


AttributeError: ignored

##Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

**Note:** Rarely in practice will you need to decide whether to use `tf.constant`
or `tf.varaible` to create tensors, as TensorFlow does this for you. However, if in odubt, use `tf.contant` and change it to
`tf.varaible` if needed. 

In [17]:
#Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for repreoductibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the orer of elements in a tensor 

In [18]:
#Shuffle your tensor (valuable when you want to shuffle your data os th inherentorder doesnt effect learning  )
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

#Shuffle our non-shuffle tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:

#Shuffle our non-shuffle tensor
tf.random.set_seed(41)
tf.random.shuffle(not_shuffled,seed = 40)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

**Exercise** Read through 
https://www.tensorflow.org/api_docs/python/tf/random/set_seed



(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)


In [44]:
@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'

bar()

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8354591], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.46399975], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)

# Other ways to make tensors

In [20]:
#Create a tendow of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
#Create a tendow of all zeros
tf.zeros(shape= (10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arrays into tensors
The main difference between Numpy arrays an TensorFlow tensors is that tensors 
can be run on a GPU (much faster for numerical computing).

In [70]:
# You can also turn Numpy arrays into tensors 
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)#create a Numpy array between 1 and 25
numpy_A

#  X = tf.constant(some_matri) #capital for matrix or tensor
#  y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [76]:
A = tf.constant(numpy_A,shape = (2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you probably nee to be aware of following modules

* Shape
* Rank
* Axis or Dimension
* Size

In [23]:
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
# Get Various attributes of our tensor
print(("Datatype of every element:",rank_4_tensor.dtype))
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor", rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))

('Datatype of every element:', tf.float32)
Number of dimensions (rank) 4
Shape of tensor (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis  5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
