In [1]:
import tensorflow as tf


# Aggregating tenor

Aggregatinf tensor = condensing them from multiple values down to a samller amount of values

In [2]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [3]:
#Get aboslute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#Let's go through the following forms of aggregation
* Get the minimum
* Get the maimum
* Get the mean
* Get the sum

In [4]:
import numpy as np 

In [5]:
#Create a tensor with random values between 0 and 100 with 50 values
E = tf.constant(np.random.randint(low = 0, high = 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 7, 20, 83, 19, 17, 50, 71, 46, 42, 32, 50, 36, 30, 28, 75, 26, 61,
       78, 61, 58, 44, 49, 91, 35, 60,  7, 39, 30, 53, 98,  1, 99, 10, 27,
       18, 75, 21, 28,  2,  3, 69, 51, 39, 35, 99, 84, 89, 62, 72, 20])>

In [6]:
#For mimimum
tf.reduce_min((E))

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
#For maimum
tf.reduce_max((E))

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [11]:
#For th sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2300>

In [13]:
import tensorflow_probability as tfp 

In [16]:
#to define variance 
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=755>

In [18]:
#For standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.48163>

In [19]:
#For standard deviation
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=755.24>

# Finding the positional maximum and minimum
This is helpful when you want to line up your labels (say `['Green', 'Blue', 'Red']`) with your prediction probabilities tensor (e.g. `[0.98, 0.01, 0.01]`).

In [20]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.16223094, 0.3909359 , 0.69363535, 0.35470869, 0.9607122 ,
       0.25963888, 0.87163379, 0.94789139, 0.3313878 , 0.29709161,
       0.55740493, 0.81356648, 0.55969725, 0.9381437 , 0.03006715,
       0.04570944, 0.58986436, 0.45752321, 0.61051223, 0.60179234,
       0.54478752, 0.1876554 , 0.22344729, 0.91805315, 0.36897955,
       0.62113759, 0.87303309, 0.04910312, 0.38597236, 0.69059142,
       0.59777389, 0.31444963, 0.27130967, 0.27942528, 0.99977427,
       0.79707544, 0.18284629, 0.05504648, 0.77623117, 0.55805382,
       0.70844161, 0.12104711, 0.74082394, 0.18635228, 0.08564717,
       0.46184684, 0.19121582, 0.0431368 , 0.16326129, 0.40767586])>

In [22]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [23]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [24]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 34
The maximum value of F is: 0.9997742671145209
Using tf.argmax() to index F, the maximum value of F is: 0.9997742671145209
Are the two max values the same (they should be)? True


In [26]:
#Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor (removing all single dimensions)
If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

`tf.squeeze()` - remove all dimensions of 1 from a tensor.

In [30]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
tf.random.set_seed(42)
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [31]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

#One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use `tf.one_hot()`.

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [33]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [34]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

#Squaring, log, square root
* `tf.square()` - get the square of every value in a tensor.
* `tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
* `tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [38]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

# H = tf.range(1,10)
#H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [39]:
# Square it
tf.square(H)
     

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [40]:
# Find the squareroot (will error), needs to be non-integer
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [43]:
H = tf.cast(H,dtype=tf.float32)

In [44]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensors and NumPy
* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

In [45]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [46]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [47]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [48]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [2]:
import tensorflow as tf

In [3]:

print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [4]:
!nvidia-smi

Sun Dec 25 01:23:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------